name: show_random_cats
description: Shower random cats image.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^6.1.1
  built_collection: ^4.3.2 
  built_value: ^7.1.0 
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  json_annotation: ^3.1.1
  flutter_bloc: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^1.0.0
  built_value_generator: ^7.1.0
  json_serializable: ^3.5.1 

flutter:

  uses-material-design: true
